# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Guardianes Monarca' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for Guardianes Monarca
  
  
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'MBProgressHUD'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
end
