target 'runin' do
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'
  pod 'FBSDKCoreKit'  
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Parse'
  pod 'MBProgressHUD'
  pod 'iOSDropDown'

  platform :ios, '10.3'

  target 'runinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      end
    end
  end

end
